# Generated by Django 4.2.23 on 2025-10-21 14:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mistral_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mistralapi',
            name='counter_id',
            field=models.CharField(default='000000', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mistralapi',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
