# Generated by Django 4.2.23 on 2025-10-21 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mistral_api', '0002_mistralapi_counter_id_mistralapi_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='mistralapi',
            name='charts_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
